// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.19;

library ImageID {
    bytes32 public constant DCAP_QUOTE_VERIFIER_ID = bytes32(0xefc7ff6a6ca56b5f1bfea11e49cab60d1255e84b465c6b0354a1ce4f95b4365f);
}
