// SPDX-License-Identifier: Apache-2.0

pragma solidity ^0.8.19;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../src/DCAPQuoteApp.sol";

/**
 * @title VerifyWithApp
 * @dev Script to verify a DCAP quote proof using our DCAP Quote Application
 */
contract VerifyWithApp is Script {
    // Our deployed DCAP Quote Application contract
    address constant DCAP_QUOTE_APP = 0x0000000000000000000000000000000000000000; // Update with actual address after deployment
    
    function run() external {
        console.log("=== VERIFYING DCAP QUOTE PROOF WITH DCAP QUOTE APP ===");
        console.log("App Contract:", DCAP_QUOTE_APP);
        
        // Read the extracted proof data from files generated by extract_from_bin.rs
        string memory sealHex = vm.readFile("./data/extracted_seal_hex.txt");
        string memory journalHex = vm.readFile("./data/extracted_journal_hex.txt");
        string memory journalDigestHex = vm.readFile("./data/extracted_journal_digest.txt");
        
        // Convert hex strings to bytes
        bytes memory seal = vm.parseBytes(sealHex);
        bytes memory journal = vm.parseBytes(journalHex);
        bytes32 journalDigest = vm.parseBytes32(journalDigestHex);
        
        console.log("Seal hex length:", bytes(sealHex).length);
        console.log("Journal hex length:", bytes(journalHex).length);
        console.log("Journal digest hex length:", bytes(journalDigestHex).length);
        console.log("Seal bytes length:", seal.length);
        console.log("Journal bytes length:", journal.length);
        console.log("Journal digest:", vm.toString(journalDigest));
        
        // Create an instance of our DCAP Quote App
        DCAPQuoteApp dcapApp = DCAPQuoteApp(DCAP_QUOTE_APP);
        
        // Verify the proof using our application
        console.log("Attempting proof verification with DCAP Quote App...");
        
        try dcapApp.verifyDCAPQuote(seal, journal) {
            console.log("PROOF VERIFICATION SUCCESSFUL!");
            console.log("The DCAP quote proof is valid and verified by our application!");
            console.log("Image ID verified:", vm.toString(dcapApp.getImageId()));
            console.log("Journal digest verified:", vm.toString(journalDigest));
            console.log("App address:", DCAP_QUOTE_APP);
        } catch Error(string memory reason) {
            console.log("VERIFICATION ERROR:");
            console.log(reason);
        } catch (bytes memory lowLevelData) {
            console.log("LOW-LEVEL ERROR:");
            console.logBytes(lowLevelData);
        }
        
        console.log("\n=== VERIFICATION COMPLETE ===");
        console.log("DCAP Quote App verification attempt completed.");
    }
}
