// SPDX-License-Identifier: Apache-2.0

pragma solidity ^0.8.19;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../src/IRiscZeroVerifier.sol";
import "../src/ImageID.sol";

/**
 * @title VerifyWithRouter
 * @dev Script to verify a DCAP quote proof using the official RISC Zero Router
 */
contract VerifyWithRouter is Script {
    // Official RISC Zero Verifier Router on Sepolia
    address constant RISC_ZERO_ROUTER = 0x925d8331ddc0a1F0d96E68CF073DFE1d92b69187;
    
    function run() external view {
        console.log("=== VERIFYING DCAP QUOTE PROOF WITH RISC ZERO ROUTER ===");
        console.log("Router Contract:", RISC_ZERO_ROUTER);
        console.log("Image ID:", vm.toString(ImageID.DCAP_QUOTE_VERIFIER_ID));
        
        // Read the extracted proof data from files generated by extract_from_bin.rs
        string memory sealHex = vm.readFile("./data/extracted_seal_hex.txt");
        string memory journalHex = vm.readFile("./data/extracted_journal_hex.txt");
        string memory journalDigestHex = vm.readFile("./data/extracted_journal_digest.txt");
        
        // Convert hex strings to bytes
        bytes memory seal = vm.parseBytes(sealHex);
        bytes memory journal = vm.parseBytes(journalHex);
        bytes32 journalDigest = vm.parseBytes32(journalDigestHex);
        
        console.log("Seal hex length:", bytes(sealHex).length);
        console.log("Journal hex length:", bytes(journalHex).length);
        console.log("Journal digest hex length:", bytes(journalDigestHex).length);
        console.log("Seal bytes length:", seal.length);
        console.log("Journal bytes length:", journal.length);
        console.log("Journal digest:", vm.toString(journalDigest));
        
        // Create an instance of the RISC Zero Router
        IRiscZeroVerifier router = IRiscZeroVerifier(RISC_ZERO_ROUTER);
        
        // Verify the proof using the official router
        console.log("Attempting proof verification with RISC Zero Router...");
        
        try router.verify(seal, ImageID.DCAP_QUOTE_VERIFIER_ID, journalDigest) {
            console.log("PROOF VERIFICATION SUCCESSFUL!");
            console.log("The DCAP quote proof is valid and verified by the official RISC Zero Router!");
            console.log("Image ID verified:", vm.toString(ImageID.DCAP_QUOTE_VERIFIER_ID));
            console.log("Journal digest verified:", vm.toString(journalDigest));
            console.log("Router address:", RISC_ZERO_ROUTER);
        } catch Error(string memory reason) {
            console.log("VERIFICATION ERROR:");
            console.log(reason);
        } catch (bytes memory lowLevelData) {
            console.log("LOW-LEVEL ERROR:");
            console.logBytes(lowLevelData);
        }
        
        console.log("\n=== VERIFICATION COMPLETE ===");
        console.log("RISC Zero Router verification attempt completed.");
    }
}
