// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "forge-std/Script.sol";
import "forge-std/console.sol";

// RISC Zero Verifier interface (standard interface)
interface IRiscZeroVerifier {
    function verify(
        bytes calldata seal,
        bytes32 imageId,
        bytes32 journalDigest
    ) external view;
}

contract VerifyGroth16FromBin is Script {
    // Our custom RISC Zero Groth16 Verifier on Sepolia
    address constant RISC_ZERO_GROTH16_VERIFIER = 0x5275C189E5e233465902fB9164e0F013519f9577;
    
    // Your DCAP Quote Verifier Image ID (actual from proof)
    bytes32 constant DCAP_QUOTE_VERIFIER_ID = 0xefc7ff6a6ca56b5f1bfea11e49cab60d1255e84b465c6b0354a1ce4f95b4365f;
    
    function run() external view {
        console.log("=== VERIFYING GROTH16 PROOF FROM BINARY RECEIPT ===");
        console.log("Verifier Contract:", RISC_ZERO_GROTH16_VERIFIER);
        console.log("Image ID:", vm.toString(DCAP_QUOTE_VERIFIER_ID));
        
        // Read the extracted proof data from files generated by extract_from_bin.rs
        string memory sealHex = vm.readFile("./data/extracted_seal_hex.txt");
        string memory journalHex = vm.readFile("./data/extracted_journal_hex.txt");
        string memory journalDigestHex = vm.readFile("./data/extracted_journal_digest.txt");
        
        // Also try to read post_state_digest if available
        string memory postStateDigestHex = "";
        try vm.readFile("./data/extracted_post_state_digest.txt") returns (string memory data) {
            postStateDigestHex = data;
        } catch {
            // File doesn't exist, that's okay
        }
        
        console.log("Seal hex length:", bytes(sealHex).length);
        console.log("Journal hex length:", bytes(journalHex).length);
        console.log("Journal digest hex length:", bytes(journalDigestHex).length);
        
        // Convert hex strings to bytes
        bytes memory seal = vm.parseBytes(sealHex);
        bytes memory journal = vm.parseBytes(journalHex);
        bytes32 journalDigest = vm.parseBytes32(journalDigestHex);
        
        console.log("Seal bytes length:", seal.length);
        console.log("Journal bytes length:", journal.length);
        console.log("Journal digest:", vm.toString(journalDigest));
        
        // Create verifier contract instance
        IRiscZeroVerifier verifier = IRiscZeroVerifier(RISC_ZERO_GROTH16_VERIFIER);
        
        // Verify the proof using the extracted data
        console.log("Attempting proof verification...");
        
        try verifier.verify(seal, DCAP_QUOTE_VERIFIER_ID, journalDigest) {
            console.log("PROOF VERIFICATION SUCCESSFUL!");
            console.log("The Groth16 proof from binary receipt is valid on-chain.");
            console.log("Image ID verified:", vm.toString(DCAP_QUOTE_VERIFIER_ID));
            console.log("Journal digest verified:", vm.toString(journalDigest));
        } catch Error(string memory reason) {
            console.log("VERIFICATION ERROR:");
            console.log(reason);
            console.log("This might be due to:");
            console.log("- Incorrect journal digest calculation");
            console.log("- Mismatched image ID");
            console.log("- Invalid seal format");
        } catch (bytes memory lowLevelData) {
            console.log("LOW-LEVEL ERROR:");
            console.logBytes(lowLevelData);
        }
        
        // Additional debugging information
        console.log("\n=== DEBUGGING INFORMATION ===");
        console.log("Seal preview (first 100 chars):", _substring(sealHex, 0, 100));
        console.log("Journal preview (first 100 chars):", _substring(journalHex, 0, 100));
        console.log("Full journal digest:", journalDigestHex);
        
        // Try alternative verification approaches if the first one fails
        console.log("\n=== TRYING ALTERNATIVE VERIFICATION APPROACHES ===");
        
        // Approach 1: Try with keccak256 of journal instead of SHA256
        bytes32 keccakJournalDigest = keccak256(journal);
        console.log("Keccak256 journal digest:", vm.toString(keccakJournalDigest));
        
        try verifier.verify(seal, DCAP_QUOTE_VERIFIER_ID, keccakJournalDigest) {
            console.log("PROOF VERIFICATION SUCCESSFUL with keccak256!");
            console.log("The Groth16 proof is valid with keccak256 journal digest.");
            return;
        } catch Error(string memory reason) {
            console.log("Keccak256 verification failed:", reason);
        } catch (bytes memory lowLevelData) {
            console.log("Keccak256 low-level error");
        }
        
        // Approach 2: Try with post_state_digest if available
        if (bytes(postStateDigestHex).length > 0 && bytes(postStateDigestHex).length == 66) {
            bytes32 postStateDigest = vm.parseBytes32(postStateDigestHex);
            console.log("Post state digest:", vm.toString(postStateDigest));
            
            try verifier.verify(seal, DCAP_QUOTE_VERIFIER_ID, postStateDigest) {
                console.log("PROOF VERIFICATION SUCCESSFUL with post_state_digest!");
                console.log("The Groth16 proof is valid with post_state_digest.");
                return;
            } catch Error(string memory reason) {
                console.log("Post state digest verification failed:", reason);
            } catch (bytes memory lowLevelData) {
                console.log("Post state digest low-level error");
            }
        }
        
        console.log("\nAll verification attempts failed.");
        console.log("Please check:");
        console.log("1. The binary receipt file exists and is valid");
        console.log("2. The extract_from_bin.rs script ran successfully");
        console.log("3. The image ID matches your deployed verifier");
        console.log("4. The journal digest calculation is correct");
    }
    
    // Helper function to get substring
    function _substring(string memory str, uint start, uint length) internal pure returns (string memory) {
        bytes memory strBytes = bytes(str);
        if (start >= strBytes.length) return "";
        if (start + length > strBytes.length) length = strBytes.length - start;
        
        bytes memory result = new bytes(length);
        for (uint i = 0; i < length; i++) {
            result[i] = strBytes[start + i];
        }
        return string(result);
    }
}
